### ISSUE TITLE
Execute preset application

### ISSUE THREAD

**Issue by allysonsouza** [felipelousantos/wp-presets#3]
Create a page, or top bar button, or widget, to execute preset application on the site. The user must have a dropdown (or other interface component) to select which preset they want to apply.

PS: Maybe we should create a default entry on plugin activation, storing the woocommerce settings and customer meta on it.

**Comment by felipelousantos** [comment]
> PS: Maybe we should create a default entry on plugin activation, storing the woocommerce settings and customer meta on it.

Great idea! I created issue #4, so we can possibly consider adding something even deeper like adding a button that allows you to create a preset based on your current settings.

**Comment by felipelousantos** [comment]
I believe that we would need something like that for doing it if I'm not missing anything:

1. Press button/element of the preset post that will trigger a function
2. This function would get all the post field values from the post selected, and it would associate these values on a variable
3. After that, the function would apply all the presets on the settings

**Comment by felipelousantos** [comment]
I had a basic implementation as part of 8cc3b14, but it still requires a full review. Also, it is currently overwriting all fields as default, but it would make more sense just applying the fields that have a value added.
